version: '3.3'

services:
   
  wordpress:
     image: wordpress:php7.2-apache
     ports:
       - 8095:80
     container_name: wrdpress-container
     environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: root
       WORDPRESS_DB_NAME: wordpress
     links:
       - mysql:mysql

  mysql:
     image: mysql:latest 
     container_name: mysql-container
     command: --default-authentication-plugin=mysql_native_password
     environment:
       MYSQL_DATABASE: wordpress
       MYSQL_ROOT_PASSWORD: root
     volumes:
       - ~/var/docker/wordpress_media:/var/lib/mysql
